name: Self-Hosted-Runner

on:
  workflow_dispatch:


jobs:
  env:
    DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
    
  Deploy:
    runs-on: self-hosted
    steps:
     - name: Code Checkout
       uses: actions/checkout@v4

     - name: Deploy with Docker-compose
       run: docker compose up -d --build
